//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "file")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub path: String,
    pub created: i64,
    pub modified: i64,
    pub orig_file_name: String,
    pub new_file_name: String,
    pub nksc_path: String,
    pub in_nx_studio: bool,
    pub tmp_lock: bool,
    pub locked: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::exif::Entity")]
    Exif,
}

// `Related` trait has to be implemented by hand
impl Related<super::exif::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Exif.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
